default: &default
  adapter:  <%= Rails.application.credentials.dig(:database, :adapter) %>
  encoding: <%= Rails.application.credentials.dig(:database, :encoding) %>
  pool:     <%= Rails.application.credentials.dig(:database, :pool) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host:     <%= Rails.application.credentials.dig(:database, :host) %>
  database: <%= Rails.application.credentials.dig(:database, :database) %>

development:
  <<: *default

test:
  <<: *default
  database: fasion_test

production:
  <<: *default
